name: Web

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Deploy ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        script: |
          cd /opt/passwall-web
          git pull
          /usr/bin/yarn install
          /usr/bin/yarn build

  #   - name: Set up Go 1.x
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ^1.13
  #     id: go

  #   - name: Check out code into the Go module directory
  #     uses: actions/checkout@v2

  #   - name: Get dependencies
  #     run: |
  #       go get -v -t -d ./...
  #       if [ -f Gopkg.toml ]; then
  #           curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  #           dep ensure
  #       fi

  #   - name: Build
  #     run: go build -v .

  #   - name: Test
  #     run: go test -v .
